sudo: required
language: python
services:
- docker

jobs:
  include:
  - stage: Check code quality
    before_install:
    - python -m pip install --upgrade pip
    install:
    - pip3 install flake8 black
    script:
    - flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - black --check .
