language: python
services:
- docker

jobs:
  include:
  - stage: Check code quality
    before_install:
    - python -m pip install --upgrade pip
    install:
    - pip3 install flake8 black
    script:
    - flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - black --check .

deploy:
  provider: pypi
  user: "__token__"
  password: "Your PyPI API token, including the pypi- prefix"
  on:
    tags: true

deploy:
  provider: snap
  snap: wilfred_*.snap
  channel: edge
  skip_cleanup: true
  on:
    tags: true