language: python
os: linux
matrix:
    include:
      - python: "3.8"
      - python: "3.7"
      - python: "3.6"
      - python: "3.5"

jobs:
    include:
        - stage: style
        install:
            - pip install black
        script:
            - black --check .
