name: wilfred # you probably want to 'snapcraft register <name>'
#base: core18 # the base snap is the execution environment for this snap
version: v0.0.4a5 # just for humans, typically '1.2+git' or '1.3.2'
summary: A CLI for managing game servers using Docker # 79 char long summary
description: |
  A CLI for managing game servers using Docker.
  
  Note: Wilfred is still under development.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  wilfred:
    command: bin/wilfred
    environment:
        PYTHONIOENCODING: utf-8

parts:
  wilfred:
    source: https://github.com/wilfred-dev/wilfred.git
    plugin: python
    python-version: python3
    build-packages:
      - python3-distutils-extra
      - build-essential
    stage-packages:
      - python3-distutils-extra
      - build-essential